name: Build for Linux

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23.1
      - name: Build
        run: go build -o archive2git
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: archive2git
          path: ./archive2git
